---

- name: 'Install Fluentd'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Install Fluentd via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://fluent.github.io/helm-charts'
        chart_ref: 'fluentd'
        release_name: 'fluentd'
        release_namespace: 'kube-logging'
        release_values:
          variant: opensearch
          plugins:
            - fluent-plugin-dedot_filter
          fileConfigs:
            02_filters.conf: |-
              <label @KUBERNETES>
                <match kubernetes.var.log.containers.fluentd**>
                  @type relabel
                  @label @FLUENT_LOG
                </match>

                # <match kubernetes.var.log.containers.**_kube-system_**>
                #   @type null
                #   @id ignore_kube_system_logs
                # </match>

                <filter kubernetes.**>
                  @type kubernetes_metadata
                  @id filter_kube_metadata
                  skip_labels false
                  skip_container_metadata false
                  skip_namespace_metadata true
                  skip_master_url true
                </filter>

                <filter **>
                  @type dedot
                  de_dot_separator _
                  de_dot_nested true
                </filter>

                <match **>
                  @type relabel
                  @label @DISPATCH
                </match>
              </label>
            04_outputs.conf: |-
              <label @OUTPUT>
                <match **>
                  @type opensearch
                  host "opensearch-cluster-master"
                  scheme https
                  ssl_verify false
                  port 9200
                  logstash_format true
                  user admin
                  password 'totallynotsecurE1@'
                </match>
              </label>

    - name: 'Wait until all pods are running'
      delegate_to: 'localhost'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-logging
      register: pod_list
      until: |
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running", "Succeeded"]
      retries: 36
      delay: 10

    - name: 'Wait until all pods are ready'
      delegate_to: 'localhost'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-logging
      register: pod_list_ready
      until: |
        pod_list_ready | json_query("resources[*].status.containerStatuses[*].ready") | unique | sort == [[true]]
      retries: 36
      delay: 10
